name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          cat << EOF > .env
          LINK_GITHUB=${{ secrets.LINK_GITHUB }}
          LINK_YOUTUBE=${{ secrets.LINK_YOUTUBE }}
          LINK_TWITTER=${{ secrets.LINK_TWITTER }}
          LINK_MASTODON=${{ secrets.LINK_MASTODON }}
          LINK_DISCORD=${{ secrets.LINK_DISCORD }}
          LINK_CODEBERG=${{ secrets.LINK_CODEBERG }}
          LINK_ITCHIO=${{ secrets.LINK_ITCHIO }}
          # Add all your other links here
          EOF

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy via SSH
        uses: https://github.com/appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/*'
          target: '~/www/voidren.com'
          strip_components: 1
